server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          searchPaths: config
          uri: https://github.com/newjiang/springcloud-config.git
          username: newjiang
          password: jiang6632380
      label: master
  application:
    name: springcloud-config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka/,http://eureka3.com:7003/eureka/
  instance:
    instance-id: springcloud-config-server-instance
    # 显示IP地址
    prefer-ip-address: true