server:
  port: 9001

spring:
  application:
    name: springcloud-feign

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka/,http://eureka3.com:7003/eureka/
  instance:
    instance-id: springcloud-feign-instance
    # 显示IP地址
    prefer-ip-address: true