server:
  port: 8001
  
mybatis:
  # mybatis配置文件所在路径
  config-location: classpath:mybatis/mybatis.cfg.xml
  # 所有Entity别名类所在包
  type-aliases-package: com.jiang.springcloud.api.model
  # mapper映射文件
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
    
spring:
   application:
    name: springcloud-provider
   datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    # 数据库名称
    url: jdbc:mysql://localhost:3306/cloud1
    username: root
    password: root
    dbcp2:
      # 数据库连接池的最小维持连接数
      min-idle: 5
      # 初始化连接数
      initial-size: 5
      # 最大连接数
      max-total: 5
      # 等待连接获取的最大超时时间
      max-wait-millis: 200

eureka:
  # 客户端-注册到eureka服务
  client:
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka/,http://eureka3.com:7003/eureka/
  instance:
    instance-id: springcloud-provider1-instance
    # 显示IP地址
    prefer-ip-address: true

info:
  app.name: springcloud-provider
  company.name: com.jiang.springcloud
  build.artifactId: $project.artifactId$
  build.version: $project.version$

